# Generated by Django 5.0.8 on 2024-08-15 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
                ('fechanacimiento', models.DateField()),
                ('rol', models.CharField(choices=[('CL', 'Cliente'), ('RC', 'Recepcionista')], default='CL', max_length=2)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AusenciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='citas.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
            ],
            options={
                'unique_together': {('dia',)},
            },
        ),
        migrations.CreateModel(
            name='HorarioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='citas.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='servicios',
            field=models.ManyToManyField(related_name='empleados', to='citas.servicio'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahorainicio', models.DateTimeField()),
                ('estado', models.IntegerField(choices=[(2, 'Cita Confirmada'), (3, 'En Proceso'), (4, 'Cita terminada'), (1, 'Cita Cancelada')], default=2)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='citas.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.servicio')),
            ],
        ),
    ]
