# Generated by Django 5.0.8 on 2024-08-07 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('descripcion_cliente', models.TextField(blank=True, max_length=2000, null=True)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('celular_cliente', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_empleado', models.CharField(max_length=10, unique=True)),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('descripcion_empleado', models.TextField(blank=True, max_length=2000, null=True)),
                ('email_empleado', models.EmailField(max_length=254)),
                ('celular_empleado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_servicio', models.CharField(max_length=10, unique=True)),
                ('nombre_servicio', models.CharField(max_length=20)),
                ('descripcion_servicio', models.TextField(max_length=200)),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cita', models.CharField(max_length=10, unique=True)),
                ('fecha_cita', models.DateField()),
                ('horainicio_cita', models.TimeField()),
                ('horafin_cita', models.TimeField()),
                ('estado_cita', models.CharField(choices=[('confirmada', 'Cita Confirmada'), ('cancelada', 'Cita Cancelada')], max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empledados', to='citas.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='citas.servicio')),
            ],
        ),
    ]
