# Generated by Django 5.0.8 on 2024-08-08 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='codigo_cita',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha_cita',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='horafin_cita',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='horainicio_cita',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='codigo_servicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='fechahora_cita',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
