# Generated by Django 5.0.8 on 2024-08-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_add_rol_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Cita Cancelada'), (2, 'Cita Confirmada'), (3, 'En Proceso'), (4, 'Cita terminada')], default=2),
        ),
    ]
