# Generated by Django 5.0.8 on 2024-08-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_cita_codigo_cita_remove_cita_fecha_cita_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='estado_cita',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='fechahora_cita',
            new_name='fechahorainicio',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='celular_cliente',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='descripcion_cliente',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email_cliente',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_cliente',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='cedula_empleado',
            new_name='cedula',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='celular_empleado',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='descripcion_empleado',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='email_empleado',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre_empleado',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='descripcion_servicio',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='nombre_servicio',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='precio_servicio',
            new_name='precio',
        ),
    ]
