# Generated by Django 5.0.8 on 2024-08-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_rename_estado_cita_cita_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='descripcion',
        ),
    ]
