# Generated by Django 5.0.8 on 2024-08-08 01:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_remove_cliente_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fechanacimiento',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
