# Generated by Django 5.0.8 on 2024-08-11 07:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_cliente_fechanacimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='citas.empleado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechanacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
