# Generated by Django 5.0.8 on 2024-08-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_empleado_servicios_alter_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='especialidad',
        ),
    ]
