# Generated by Django 5.0.8 on 2024-08-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_ausenciaempleado_horarioempleado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horarioempleado',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='horarioempleado',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Viernes')]),
        ),
    ]
