# Generated by Django 5.0.8 on 2024-08-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_alter_cita_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={},
        ),
    ]
