# Generated by Django 5.0.8 on 2024-08-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0012_alter_empleado_options_alter_servicio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.IntegerField(choices=[(2, 'Cita Confirmada'), (1, 'Cita Cancelada')]),
        ),
    ]
